BCDevExchange/devex

- modules/projects/server/controllers/projects.server.controller.js
doc(projects):  Changed credentials for developer / test in the github language elements in projects.server.controller.js
> Dewolfe001 pull request

- modules/core/client/app/init.js
- modules/core/client/views/home.client.view.html
```
Header
Blank Line
Body
Blank Line
Footer
Fixes #82
```
* Types: 
* Scope:
* Subject: …
> last few changes  on top of earlier commits

- modules/core/client/css/core.css
- modules/core/client/views/roadmap.view.html
- modules/opportunities/client/views/edit-opportunity.client.view.html
- modules/users/client/views/settings/edit-profile.client.view.html
- modules/users/client/views/settings/settings.client.view.html
- update heading and spacing to match with other class="static" pages on the site
- made profile picture and user's public profile more prominent
- added extra information to explain when the user's public profile info would display
- clearer Notifications heading
- separate heading for the public sector checkbox, with additional info to explain that users can create content on the site
- implemented consistent use of class="alert" in place of "well" and "panel"
> Mw profile ui

- .s2i/bin/assemble
- .s2i/bin/save-artifacts
> S2I changes for incremental compilation

- Jenkinsfile
- functional-tests/src/test/groovy/FlowSpecs.groovy
- functional-tests/src/test/groovy/LoginModule.groovy
- functional-tests/src/test/groovy/pages/app/HomePage.groovy
- functional-tests/src/test/groovy/pages/app/OpportunityDetail.groovy
- functional-tests/src/test/groovy/pages/app/SignedIn.groovy
Additional BDD tests for Devex.  As stated in the comments the test should be extended to include logging in as admin and creating an issue.
> Updated BDD tests

- Jenkinsfile
```
Header
Blank Line
Body
Blank Line
Footer
Fixes #82
```
* Types: 
* Scope:
* Subject: …
> Updated Jenkinsfile with different method of passing test credentials

- Jenkinsfile
- modules/users/client/directives/users.client.directive.js
Jenkinsfile: 
add timeoiut to input request
user.client.directive.js:
remove invisible 1st character, was likely a copy/paste product
> Jenkinsfile and user.client.directive.js update

- Jenkinsfile
- Jenkinsfile.bdd
- Jenkinsfile.master
Added new Jenkinsfile for master and functional testing. Added new functionality to all Jenkinsfiles, like archive of test results, etc.
> Jenkinsfile modifications

- Jenkinsfile
- Jenkinsfile.dbbstack
```
Header
Blank Line
Body
Blank Line
Footer
Fixes #82
```
* Types: 
* Scope:
* Subject: …
> Jenkinsfile swith to BDDStack functional test env

- functional-tests/src/test/groovy/FlowSpecs.groovy
```
Header
Blank Line
Body
Blank Line
Footer
Fixes #82
```
* Types: 
* Scope:
* Subject: …
> flowspecs update

- functional-tests/src/test/groovy/OpportunityCreateSpecs.groovy
- functional-tests/src/test/groovy/pages/app/OpportunitiesAdminCreatePage.groovy
- functional-tests/src/test/groovy/pages/app/OpportunitiesAdminEditPage.groovy
- functional-tests/src/test/groovy/pages/app/OpportunitiesPage.groovy
- functional-tests/src/test/groovy/pages/app/OpportunityDetailPage.groovy
```
Header
Blank Line
Body
Blank Line
Footer
Fixes #82
```
* Types: 
* Scope:
* Subject: …
> Creation of opportunity test script.

- Jenkinsfile.master
- functional-tests/src/test/groovy/OpportunityCreateSpecs.groovy
- functional-tests/src/test/groovy/pages/app/OpportunityDetailPage.groovy
```
Header
Blank Line
Body
Blank Line
Footer
Fixes #82
```
* Types: 
* Scope:
* Subject: …
>  Finalise the create/publish opportunity test

- functional-tests/src/test/groovy/extensions/AngularJSAware.groovy
```
Header
Blank Line
Body
Blank Line
Footer
Fixes #82
```
* Types: 
* Scope:
* Subject: …
> No longer required to inject my own js as it is in the app

- functional-tests/build.gradle
- functional-tests/src/test/resources/GebConfig.groovy
```
Header
Blank Line
Body
Blank Line
Footer
Fixes #82
```
* Types: 
* Scope:
* Subject: …
> Include safari support

- functional-tests/src/test/groovy/FlowSpecs.groovy
- functional-tests/src/test/groovy/OpportunityCreateSpecs.groovy
- functional-tests/src/test/groovy/pages/app/HomePage.groovy
```
Header
Blank Line
Body
Blank Line
Footer
Fixes #82
```
* Types: 
* Scope:
* Subject: …
> updates to test specs

- functional-tests/src/test/groovy/FlowSpecs.groovy
- functional-tests/src/test/groovy/modules/LoginModule.groovy
- functional-tests/src/test/groovy/pages/app/HomePage.groovy
```
Header
Blank Line
Body
Blank Line
Footer
Fixes #82
```
* Types: 
* Scope:
* Subject: …
> Updates to test scripts due to main page changes.

- Jenkinsfile
- functional-tests/build.gradle
```
Header
Blank Line
Body
Blank Line
Footer
Fixes #82
```
* Types: 
* Scope:
* Subject: …
> BDDStack Reporting updates

- functional-tests/build.gradle
```
Header
Blank Line
Body
Blank Line
Footer
Fixes #82
```
* Types: 
* Scope:
* Subject: …
> Updated Spock report version

- modules/core/client/directives/forms.client.directive.js
- modules/proposals/client/controllers/proposals.client.controller.js
- modules/proposals/client/views/edit-proposal.client.view.html
fix(proposals): Fixes high priority bugs with Unsaved Changes Modal
Adds warn-on-exit directive to proposal form.
Updates warnOnExit scope listeners so URL and state changes are correctly intercepted and handled.
Updates proposal form controller to reset pristine state whenever actions such as save, delete, submit and withdraw are performed.
Removes deprecated modal logic from proposal form controller since directive now handles confirmation prompts.
Fixes #187, Fixes #188
> Amanji directive bug fixes

- modules/core/client/directives/forms.client.directive.js
- modules/proposals/client/controllers/proposals.client.controller.js
fix(proposals): Fixes high priority bugs with Unsaved Changes Modal
Adds warn-on-exit directive to proposal form.
Updates warnOnExit scope listeners so URL and state changes are correctly intercepted and handled.
Updates proposal form controller to reset pristine state whenever actions such as save, delete, submit and withdraw are performed.
Removes deprecated modal logic from proposal form controller since directive now handles confirmation prompts.
Fixes #187, Fixes #188
> Priority Bug Fixes

- modules/notifications/server/controllers/notifications.server.controller.js
- modules/proposals/client/controllers/proposals.swu.client.controller.js
- modules/proposals/client/css/proposals.css
- modules/proposals/client/views/swu-proposal-edit.html
feature(proposals): BA-432 Team picker improvements
This PR addresses the improvements outlined in BA-432, including the addition of a filter/search box for team members and a pagination control.  This should improve the experience for selecting team members of large teams.
Fixes BA-432
> BA-432 Team Picker improvements

- Dockerfile
- dev.sh
fix(dev-script)
Modifications to dev.sh to allow Docker mappings on Windows
FIxes BA-487
> BA-487 - Added OS detection, updated deprecated MAINTAINER command

- modules/proposals/client/views/swu-proposal-edit.html
- modules/proposals/server/models/proposal.server.model.js
BA-544 - Adding new tab for Addendum
This is a new tab for Addendum.
Fixes BA-544
> BA-544 - Adding Addendum tab to proposal edit view

- modules/core/client/css/core.css
- modules/core/client/services/modalService.client.service.js
- modules/messages/client/views/message-view.html
- modules/opportunities/client/css/opportunities.css
- modules/opportunities/client/views/swu-opportunity-modal-code-challenge.html
- modules/opportunities/client/views/swu-opportunity-modal-interview.html
- modules/opportunities/client/views/swu-opportunity-modal-question-vetting.html
- public/less/include/modals.less
@SteveChapmanBCDX - please review - thanks. 
- updated formatting of modal styles - sm, md, and lg
- made lg modals so that the buttons stick to the bottom of display
- updated html file for the modal for question vetting to make consistent with other modals in the Evaluation module
> BA-686 /// improve format of large (full-screen) modals

- config/env/development.js
- config/lib/express.js
- config/lib/seed.js
Made optional to use shared or pooled connection, can switch between for either warnings or performance
> BA-698 Potential memory leak from session storage

- config/env/development.js
- config/lib/seed.js
- modules/core/client/views/header.client.view.html
could not replicate locally, but this fix should take care of the flicker
> BA-729 nav bar flicker

- modules/users/server/controllers/admin.server.controller.js
this was an out of sync call to next that would occur while a save was still happening
> BA-604 uncaught exception

- modules/orgs/server/controllers/orgs.server.controller.js
- modules/proposals/client/directives/proposals.client.directives.js
fix(org): Fixed save company when no capabilities are created.
- Unhandled exception happening while creating a company when no 
capabilities were previously created
fix(proposal): List page was breaking when no opportunities are created.
- Unhandled exception when retrieving stats from a undefined opportunity.
> Bug fixes on scopes Org and Proposal

- modules/users/client/views/settings/profile-privacy.html
weird dynamic html issue, fixed with a silly hack
> BA-322 profile email input not working

- modules/opportunities/client/directives/opportunities.client.directives.js
- modules/opportunities/client/views/opportunity-list-directive.html
added another stage in loading (this should have been handled through a resolve, but the directive is necessary, so ......
> BA-727 no ops display erroneously

- modules/capabilities/client/config/capabilities.client.routes.js
- modules/messages/client/config/messages.routes.js
- modules/opportunities/client/config/opportunities.client.routes.js
- modules/orgs/client/config/orgs.client.routes.js
- modules/programs/client/config/programs.client.routes.js
- modules/projects/client/config/projects.client.routes.js
- modules/proposals/client/config/proposals.client.routes.js
- modules/propsalQuestions/client/config/propsalQuestions.client.routes.js
- modules/superbasics/client/config/superbasics.client.routes.js
single page app issue when page remembers scroll position - nested ui-views not autoscrolling - added this everywhere I could find
> BA-730 page does not scroll to top

- Dockerfile
- dev.sh
- package.json
- yarn.lock
- Add yarn to `Dockerfile`
- Update `yarn.lock`
- Refactor `package.json` to support yarn workflow
- Suppress error message in `dev.sh`
> BA-756 Replace NPM with Yarn

- .s2i/bin/assemble
- Dockerfile
- package.json
- Add yarn install to `assemble`
- Move build step out of post-install in `package.json`
- Update `Dockerfile`
> Fix pipeline build (S2I)

- modules/opportunities/client/views/swu-opportunity-eval-directive.html
fix(evaluation): Round all number fields to 2 decimal places
Occasionally, numbers would overflow when added.  This fix forces the number fields to 2 decimal places.
Fixes BA-888.
> BA-888 - Round all number fields in eval to 2 decimal places

- modules/orgs/client/controllers/orgs.client.controller.js
- modules/orgs/client/css/orgs.css
- modules/orgs/client/views/org-edit.html
- modules/orgs/client/views/org-main.html
fix(org): Enforce protocol selection when specifying company website
- Add a protocol selector for http/https
- Add logic for putting together address and selected protocol
- Clean up unused/commented out code
Fixes BA-331
> BA-331 - Fix broken org links if protocol not specified

- modules/opportunities/client/controllers/opportunities.swu.client.controller.js
- modules/opportunities/client/css/opportunities.css
- modules/opportunities/client/directives/opportunities.eval.directive.js
- modules/opportunities/client/views/swu-opportunity-edit-scoring.html
- modules/opportunities/client/views/swu-opportunity-edit.html
- modules/opportunities/server/models/opportunity.server.model.js
- public/less/include/bc-devx.less
fix(opportunities): Add edit view for entering opportunity stage weights to be used during evaluation
* Update data model for opportunities to stores stage weights
* Update evaluation logic to use values from data model
* Add edit tab for Scoring for the government actor to update/view weights
Fixes BA-900.
> BA-900 - Change stage weighting/scoring to be opportunity specific

- modules/opportunities/client/views/cwu-opportunity-edit-description.html
- Removed the misspelled "chanracter" counter
- Removed some old commented out code
> BA-715 - Remove character counter for Background tab textbox

- functional-tests/src/test/groovy/OpportunityCreateSpecs.groovy
- functional-tests/src/test/groovy/pages/app/OpportunitiesAdminCreatePage.groovy
- modules/opportunities/client/services/opportunities.client.service.js
- modules/opportunities/client/views/cwu-opportunity-edit-details.html
- modules/users/server/controllers/users/users.profile.server.controller.js
Removed element entitled "Email to Receive Acceptance of Terms and Contract".  This field is no longer required.
BA-69 - Remove logic preventing publication
Removed logic test preventing publication when "Email to Receive Acceptance of Terms and Contract" field was empty.
> BA-69 - Remove unnecessary CWU element

- README.md
- modules/proposals/client/views/list.proposals.directive.html
Removed "Views" elements from stats bar on opportunity page.
> BA-340 - Remove "Views" element from Opportunity page

- modules/opportunities/client/views/cwu-opportunity-view.html
- modules/proposals/client/views/cwu-proposal-view.html
- modules/proposals/client/views/list.proposals.directive.html
styling(CWU proposals): restyling how received CWU proposals look
Fixes BA-879
> BA-879 // Restyle view for CWU proposals

- modules/opportunities/client/views/cwu-opportunity-view.html
Replaced countdown timer (days, hours, minutes remaining) with static text.  This change mirrors that in SWU.
> BA-365 - Replace CWU countdown timer with static deadline

- modules/opportunities/client/services/opportunities.client.service.js
- modules/opportunities/server/controllers/opportunities.server.controller.js
- modules/opportunities/server/routes/opportunities.server.routes.js
- modules/proposals/client/controllers/proposals.swu.client.controller.js
feat(proposals): Add check for passed opportunity deadline
- Add service route for checking deadline on server
- Add logic in proposal client to prevent editing/submit after deadline
Fixes BA-940.
> BA-940 - Add check for passed opportunity deadline

- modules/core/client/config/core.client.route-filter.js
fix(login): Fix broken redirect after login
- Fix redirect after login that broke with AngularJS upgrade
- Use ui-router transitions instead of deprecated onStateChange
Fixes BA-953.
> BA-953 - Update ui-router to use transitions

- modules/proposals/client/controllers/proposals.client.controller.js
- modules/proposals/client/views/cwu-proposal-edit-attachments.html
fix(proposals): Fix bug where CWU proposals can be submitted after deadline
- Extra request to retrieve deadline from server
- Clean-up CWU controller
Fixes BA-947.
> BA-947 - Fix ability to submit CWU proposal after deadline

- modules/proposals/client/controllers/proposals.client.controller.js
Modified logic in "copyUserInfo" function.
> BA-947 - Logic Change

- Dockerfile
- tslint.json
Modified Dockerfile.js to remove references to Bower
Added new rule to tslint configuration file.
> BA-1031 - Modify Dockerfile.js to remove references to Bower

- modules/opportunities/client/views/cwu-opportunity-view.html
fix(proposals): Show company name if assigned proponent submitted as a company
- Previously an individual user name was shown regardless of how proposal was submitted
Fixes BA-1035.
> BA-1035 - Show company if CWU proposal submitted as such

- config/env/default.js
feat(express): Enable CSRF for angular
Fixes BA-1043.
> BA-1043 - Enable CSRF for angular

- modules/proposals/server/controllers/ProposalsServerController.ts
- modules/users/server/policies/UserPolicy.ts
fix(proposals): Fix policy on proposal
- Update user policy for admin access
- Restrict proposal get/post
Fixes BA-1063.
> BA-1063 - Fix proposal policy/controller

- modules/programs/client/controllers/programs.client.controller.js
- modules/programs/client/views/edit-program.client.view.html
- modules/programs/client/views/list.programs.directive.html
- modules/programs/server/models/ProgramModel.ts
- modules/projects/client/controllers/projects.client.controller.js
- modules/projects/client/views/edit-project.client.view.html
- modules/projects/server/models/ProjectModel.ts
fix(programs/projects): Fix models, broken buttons on programs/projects
- Adjust misaligned buttons
- Fix broken close on edit view
Fixes BA-1065.
> BA-1065 - Fix models on programs/projects

- README.md
Here are some steps to share with the community for how to get this working on Linux and with downgrading Node to a compatible version.
> Updated the readme for linux and nvm

- modules/users/server/controllers/users/UserAuthenticationController.ts
fixes(auth): Disallow linking of accounts using different OAuth providers
- Disable ability to link multiple oauth providers
Fixes BA-1071.
> BA-1071 - Remove additionalProvider logic

- config/message-templates/opportunities/approval-request.html
- config/message-templates/opportunities/pre-approval-request.html
- modules/opportunities/client/controllers/OpportunityViewCWUController.ts
- modules/opportunities/client/views/cwu-opportunity-edit-approval.html
- modules/opportunities/server/models/OpportunityModel.ts
- modules/opportunities/shared/IOpportunityDTO.d.ts
- modules/users/server/controllers/users/UserAuthenticationController.ts
fixes(approvals): Add missing resource field to opportunity approval form.
- Add new field
- Update contract data schema
- Update message/email templates
- Update approval export PDF
Fixes BA-1085.
> BA-1085 - Add staff resource field to opp approval form

- modules/proposals/client/views/swu-proposal-view.html
- modules/proposals/server/controllers/ProposalsServerController.ts
feat(proposals): Fix issue where contact info was not populating on SWU proposal view
- Also remove redundant skill list on POC
Fixes BA-1088.
> BA-1088 - Fix missing contact info on SWU proposal view

- README.md
- dev.sh
- package.json
- sample.env
feat(dev): Update documentation and improve overall development experience
- Update README.md and remove out of date sections
- Set application to use port 3000 when running in docker
- Add clarity around environment variables (or at least attempt to)
Fixes BA-1089.
> BA-1089 - Update documentation/improve dev experience

- modules/opportunities/server/controllers/OpportunitiesServerController.ts
GitHub issues were having the deadline date displayed in UTC, but failed
to indicate the timezone. This lead to confusion and inconsistencies
with the BCDevExchange website.
Fixes #551
Issues will now look like this:
While the Opportunity on BCDevExchange displays:
> fix(opportunities): GitHub issues should display deadline in PST

- modules/opportunities/client/services/OpportunitiesService.ts
- modules/proposals/client/controllers/ProposalEditCWUController.ts
- modules/proposals/client/controllers/ProposalEditSWUController.ts
fix(proposals): Fix issues around proposal deadlines and editing
Fixes BA-1093.
> BA-1093 - Fix proposal submission deadline

- modules/orgs/client/views/list-orgs.client.view.html
- modules/orgs/client/views/list.orgs.directive.html
- public/sass/include/_bc-devx.scss
- public/sass/include/_tables.scss
Lots of styling fiddling for a more minimal and responsive companies list:
> Companies list styling changes

- modules/opportunities/client/directives/OpportunityEvaluationDirective.ts
- modules/opportunities/shared/IOpportunityDTO.d.ts
- modules/proposals/client/controllers/ProposalEditSWUController.ts
- modules/proposals/server/models/ProposalModel.ts
fix(proposals): Synchronize current skillset for proposal team members during evaluation.
Fixes BA-1091.
> BA-1091 - Sync proposal eval and user skills

- modules/core/client/views/home.client.view.html
- modules/core/client/views/sprintwithus.view.html
- modules/opportunities/client/config/OpportunityRouter.ts
- modules/opportunities/client/controllers/OpportunityListController.ts
- modules/opportunities/client/views/opportunity-list.html
- public/sass/include/_bc-devx.scss
- public/sass/include/_cards.scss
- public/sass/include/_variables.scss
> Banner fixes

- modules/opportunities/client/views/cwu-opportunity-view.html
- modules/opportunities/client/views/swu-opportunity-view.html
styling(opportunities)
Fiddled with classes on opportunity details on CWU and SWU opportunity pages to make them display better on small displays.
Fixes BA-1060
> BA-1060 - Make opp details responsive on small displays (CWU and SWU)

- modules/orgs/client/views/list.orgs.directive.html
- modules/users/client/controllers/settings/EditProfileController.ts
- modules/users/client/views/settings/profile-main.html
- public/sass/include/_bc-devx.scss
fix(user): Fix sign persistence on profile deletion
- Include minor cosmetic adjustments on org list and user profile
Fixes BA-1109.
> BA-1109 - Fix sign-in persistence on profile deletion

- modules/orgs/client/controllers/OrgCreateController.ts
- modules/orgs/client/views/org-add.html
fix(orgs): Fixes non-functional cancel button for orgs
Fixes BA-1098
> BA-1098 - Fixes non-functional cancel

- modules/opportunities/server/controllers/OpportunitiesServerController.ts
- modules/programs/server/controllers/ProgramsServerController.ts
- modules/projects/server/controllers/ProjectsServerController.ts
fix(opportunities, programs, projects): Prevent unauthorized users from viewing unpublished opportunities, programs and projects
Fixes BA-1165
> BA-1165 - Prevent unauthorized users from viewing unpublished opportunities, programs, and projects 

- modules/opportunities/client/views/cwu-opportunity-view.html
- modules/opportunities/client/views/swu-opportunity-edit.html
- modules/programs/client/views/view-program.client.view.html
- modules/projects/client/views/list.projects.directive.html
- modules/projects/client/views/view-project.client.view.html
fix(programs, projects, opportunities): Fix publish buttons so that they work as expected in Firefox
- Removed the href value 'javascript:void(0);' from a number of publish, unpublish and delete buttons so that they work as expected in Firefox
Fixes BA-1111
> BA-1111: Fix publish buttons so that they work in Firefox

- modules/core/server/views/layout.server.view.html
- public/unsupported/index.html
fix(core): Add a landing page for anyone attempting to access the site through Internet Explorer
Fixes BA-1113
> BA-1113: Add landing page for unsupported browsers

- modules/opportunities/client/directives/OpportunityEvaluationDirective.ts
- modules/opportunities/client/services/OpportunitiesService.ts
- modules/opportunities/server/controllers/OpportunitiesServerController.ts
- modules/opportunities/server/policies/OpportunitiesPolicy.ts
- modules/opportunities/server/routes/OpportunitiesRouter.ts
- modules/proposals/server/controllers/ProposalsServerController.ts
fix(opportunities, proposals): Refactor SWU opportunity assignment so that the opportunity and proposal both get updated on the server side
- Modifies the OpportunityEvaluationDirective so that it now calls the OpportunitiesServerController where the opportunity gets updated. The OpportunitiesServerController then now calls the ProposalsServerController where the proposal gets updated
Fixes BA-1166
> BA-1166 - Refactor SWU opportunity assignment

- modules/opportunities/server/controllers/OpportunitiesServerController.ts
- modules/opportunities/server/utilities/OpportunitiesUtilities.ts
Limit proposal data retrievable from opportunities endpoint as non-admin.
> Limit proposal info as non-admin

- modules/opportunities/server/controllers/OpportunitiesServerController.ts
Adjustment to account for old data model on proposals
> Adjustment for previous data model change

- config/email-templates/opportunities/opportunity-assign-cwu-email.html
- config/email-templates/opportunities/opportunity-assign-swu-email.html
- config/message-templates/opportunities/opportunity-assign-cwu-msg.html
- modules/proposals/server/controllers/ProposalsServerController.ts
Also fix issue with email templates.
> Fix issue with team questions not persisting

- modules/opportunities/client/views/cwu-opportunity-view.html
- modules/opportunities/server/controllers/OpportunitiesServerController.ts
This PR includes a fix for broken images on CWU for the winning proponent.
> Fix winning proponent image on CWU
